image: eu.gcr.io/gitpod-core-dev/dev/dev-environment:aledbf-cilint-fork.0
workspaceLocation: gitpod/gitpod-ws.code-workspace
checkoutLocation: gitpod
ports:
  - port: 1337
    onOpen: open-preview
  - port: 3000
    onOpen: ignore
  - port: 3001
    onOpen: ignore
  - port: 3306
    onOpen: ignore
  - port: 4000
    onOpen: ignore
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
    visibility: private
  - port: 9229
    onOpen: ignore
# Go proxy
  - port: 9999
    onOpen: ignore
  - port: 13001
    onOpen: ignore
# Werft
  - port: 7777
    onOpen: ignore
# Dev Theia
  - port: 13444
tasks:
  - name: Test Command
    init: export PARAMS=${PARAMS:-"100_200ms_5m"}; go run ./main.go $PARAMS
vscode:
  extensions:
    - hangxingliu.vscode-nginx-conf-hint
    - zxh404.vscode-proto3
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - bajdzis.vscode-database
    - hashicorp.terraform
    - stkb.rewrap
    - golang.go
